# https://goreleaser.com/customization/project/
project_name: kai-kli

# https://goreleaser.com/customization/release/
release:
  prerelease: auto
  name_template: "Konstellation CLI {{.Version}}"
  github:
    owner: konstellation-io
    name: kai-kli
  # Append to the release published by Nyx.
  mode: append
# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - go mod tidy
    - go mod download

# https://goreleaser.com/customization/builds/
builds:
  - <<: &build_defaults
      binary: bin/kli
      main: ./cmd/main.go
      env:
        - GO111MODULE=on
        - CGO_ENABLED=0
      ldflags:
        - -s -w -X main.version={{.Version}}
        - -X main.date={{time "2006-01-02"}}
    id: macos
    goos: [darwin]
    goarch: [amd64, arm64]
  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: [amd64, arm64]
  - <<: *build_defaults
    id: windows
    goos: [windows]
    goarch: [amd64, arm64]

# https://goreleaser.com/customization/archive/
archives:
  - <<: &archive_defaults
      name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}-{{ .Arch }}"
      wrap_in_directory: true
      files:
        - LICENSE
    id: nix
    builds: [macos, linux]
    format: tar.gz
  - <<: *archive_defaults
    id: windows-zip
    builds: [windows]
    format: zip

# https://goreleaser.com/customization/nfpm/
nfpms:
  - license: MIT
    maintainer: Konstellation
    homepage: https://github.com/konstellation-io/kai-kli
    description: CLI tool to manage Konstellation
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}-{{ .Arch }}"
    bindir: /usr
    formats:
      - deb
      - rpm

#https://goreleaser.com/customization/homebrew/
brews:
  - name: kli
    repository:
      owner: konstellation-io
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage:  https://github.com/konstellation-io/kai-kli
    description: A CLI to access, query and manage KAI servers.
    commit_author:
      name: goreleaserbot
      email: releases@konstellation.io

scoops:
  - name: kli
    commit_author:
      name: goreleaserbot
      email: releases@konstellation.io
    commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Version }}"
    homepage: https://github.com/konstellation-io/kai-kli
    description: A CLI to access, query and manage KAI servers.
    license: MIT
    repository:
      owner: konstellation-io
      name: scoop-bucket
      branch: main
      token: "{{ .Env.SCOOP_BUCKET_GITHUB_TOKEN }}"
      pull_request:
        enabled: false

dockers:
  - image_templates:
      - "konstellation/{{.ProjectName}}:{{ .Tag }}"
      - "konstellation/{{.ProjectName}}:latest"
    use: buildx
    ids:
      - "linux"
    dockerfile: Dockerfile

# https://goreleaser.com/customization/checksum/
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

# https://goreleaser.com/customization/changelog/
changelog:
  skip: true # This part will be handled by Nyx
