// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	product "github.com/konstellation-io/kli/api/kai/product"
	version "github.com/konstellation-io/kli/api/kai/version"
)

// MockKaiClient is a mock of Client interface.
type MockKaiClient struct {
	ctrl     *gomock.Controller
	recorder *MockKaiClientMockRecorder
}

// MockKaiClientMockRecorder is the mock recorder for MockKaiClient.
type MockKaiClientMockRecorder struct {
	mock *MockKaiClient
}

// NewMockKaiClient creates a new mock instance.
func NewMockKaiClient(ctrl *gomock.Controller) *MockKaiClient {
	mock := &MockKaiClient{ctrl: ctrl}
	mock.recorder = &MockKaiClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKaiClient) EXPECT() *MockKaiClientMockRecorder {
	return m.recorder
}

// Product mocks base method.
func (m *MockKaiClient) Product() product.ProductInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Product")
	ret0, _ := ret[0].(product.ProductInterface)
	return ret0
}

// Product indicates an expected call of Product.
func (mr *MockKaiClientMockRecorder) Product() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Product", reflect.TypeOf((*MockKaiClient)(nil).Product))
}

// Version mocks base method.
func (m *MockKaiClient) Version() version.VersionInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Version")
	ret0, _ := ret[0].(version.VersionInterface)
	return ret0
}

// Version indicates an expected call of Version.
func (mr *MockKaiClientMockRecorder) Version() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Version", reflect.TypeOf((*MockKaiClient)(nil).Version))
}
