// Code generated by MockGen. DO NOT EDIT.
// Source: process_registry.go

// Package mocks is a generated GoMock package.
package mocks

import (
	os "os"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	configuration "github.com/konstellation-io/kli/internal/services/configuration"
)

// MockProcessRegistryInterface is a mock of ProcessRegistryInterface interface.
type MockProcessRegistryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockProcessRegistryInterfaceMockRecorder
}

// MockProcessRegistryInterfaceMockRecorder is the mock recorder for MockProcessRegistryInterface.
type MockProcessRegistryInterfaceMockRecorder struct {
	mock *MockProcessRegistryInterface
}

// NewMockProcessRegistryInterface creates a new mock instance.
func NewMockProcessRegistryInterface(ctrl *gomock.Controller) *MockProcessRegistryInterface {
	mock := &MockProcessRegistryInterface{ctrl: ctrl}
	mock.recorder = &MockProcessRegistryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcessRegistryInterface) EXPECT() *MockProcessRegistryInterfaceMockRecorder {
	return m.recorder
}

// Register mocks base method.
func (m *MockProcessRegistryInterface) Register(server *configuration.Server, processFile *os.File, productID, processID, processType, version string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", server, processFile, productID, processID, processType, version)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockProcessRegistryInterfaceMockRecorder) Register(server, processFile, productID, processID, processType, version interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockProcessRegistryInterface)(nil).Register), server, processFile, productID, processID, processType, version)
}
